### ISSUE TITLE
How to test the inference speed of exported onnx models?

### ISSUE THREAD

**Issue by TheSunWillRise** [facebookresearch/GPU-DPF#1]
Hello,  thanks for your great work.
I have a question about the codes. If  I have trained a model and exported an onnx model, for example, I got the onnx model by running `paper/experimental/batch_pir/modules/language_model/train_model.sh`.
How can I test the inference speed of this onnx model using dpf?

**Comment by agnusmaximus** [comment]
Hi, we don't expose any of the model code for the project, only the DPF-PIR code.
